version: '3'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: user_todo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: api_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user_todo
      DB_PASS: 123
      DB_NAME: api_todo
    ports:
      - "9000:9000"

volumes:
  postgres_data:
